// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(OhMyGrepCoreFFI)
    import OhMyGrepCoreFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ohmygrep_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ohmygrep_core_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

/**
 * Cancellation token for in-flight searches. Construction takes an
 * optional timeout (deadline = now + timeout). `is_cancelled` returns
 * true if either an explicit `cancel()` was called or the deadline
 * elapsed. The deadline is immutable after construction.
 */
public protocol CancelTokenProtocol: AnyObject {
    func cancel()

    func isCancelled() -> Bool
}

/**
 * Cancellation token for in-flight searches. Construction takes an
 * optional timeout (deadline = now + timeout). `is_cancelled` returns
 * true if either an explicit `cancel()` was called or the deadline
 * elapsed. The deadline is immutable after construction.
 */
open class CancelToken:
    CancelTokenProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ohmygrep_core_fn_clone_canceltoken(self.pointer, $0) }
    }

    public convenience init(timeoutMs: UInt64?) {
        let pointer =
            try! rustCall {
                uniffi_ohmygrep_core_fn_constructor_canceltoken_new(
                    FfiConverterOptionUInt64.lower(timeoutMs), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ohmygrep_core_fn_free_canceltoken(pointer, $0) }
    }

    open func cancel() {
        try! rustCall {
            uniffi_ohmygrep_core_fn_method_canceltoken_cancel(self.uniffiClonePointer(), $0)
        }
    }

    open func isCancelled() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_ohmygrep_core_fn_method_canceltoken_is_cancelled(self.uniffiClonePointer(), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCancelToken: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = CancelToken

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> CancelToken {
        return CancelToken(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: CancelToken) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CancelToken {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: CancelToken, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCancelToken_lift(_ pointer: UnsafeMutableRawPointer) throws -> CancelToken {
    return try FfiConverterTypeCancelToken.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCancelToken_lower(_ value: CancelToken) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCancelToken.lower(value)
}

/**
 * A search running on a background thread whose matches are pulled in batches.
 */
public protocol SearchSessionProtocol: AnyObject {
    /**
     * Blocks until at least one match is available or the search ends, then returns
     * up to `max` matches. The final batch carries the summary; after a cancel it
     * arrives without draining buffered matches.
     */
    func nextBatch(max: UInt32) throws -> SearchBatch
}

/**
 * A search running on a background thread whose matches are pulled in batches.
 */
open class SearchSession:
    SearchSessionProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ohmygrep_core_fn_clone_searchsession(self.pointer, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ohmygrep_core_fn_free_searchsession(pointer, $0) }
    }

    /**
     * Validates the request synchronously, then starts the walk.
     */
    public static func start(request: SearchRequest, cancel: CancelToken) throws -> SearchSession {
        return try FfiConverterTypeSearchSession.lift(rustCallWithError(FfiConverterTypeOhMyGrepError.lift) {
            uniffi_ohmygrep_core_fn_constructor_searchsession_start(
                FfiConverterTypeSearchRequest.lower(request),
                FfiConverterTypeCancelToken.lower(cancel), $0
            )
        })
    }

    /**
     * Blocks until at least one match is available or the search ends, then returns
     * up to `max` matches. The final batch carries the summary; after a cancel it
     * arrives without draining buffered matches.
     */
    open func nextBatch(max: UInt32) throws -> SearchBatch {
        return try FfiConverterTypeSearchBatch.lift(rustCallWithError(FfiConverterTypeOhMyGrepError.lift) {
            uniffi_ohmygrep_core_fn_method_searchsession_next_batch(self.uniffiClonePointer(),
                                                                    FfiConverterUInt32.lower(max), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchSession: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SearchSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SearchSession {
        return SearchSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SearchSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SearchSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> SearchSession {
    return try FfiConverterTypeSearchSession.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchSession_lower(_ value: SearchSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSearchSession.lower(value)
}

/**
 * One `SearchSession::next_batch` result; `summary` is set on the final batch only.
 */
public struct SearchBatch {
    public var matches: [SearchMatch]
    public var summary: SearchSummary?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(matches: [SearchMatch], summary: SearchSummary?) {
        self.matches = matches
        self.summary = summary
    }
}

extension SearchBatch: Equatable, Hashable {
    public static func == (lhs: SearchBatch, rhs: SearchBatch) -> Bool {
        if lhs.matches != rhs.matches {
            return false
        }
        if lhs.summary != rhs.summary {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(matches)
        hasher.combine(summary)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchBatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchBatch {
        return
            try SearchBatch(
                matches: FfiConverterSequenceTypeSearchMatch.read(from: &buf),
                summary: FfiConverterOptionTypeSearchSummary.read(from: &buf)
            )
    }

    public static func write(_ value: SearchBatch, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeSearchMatch.write(value.matches, into: &buf)
        FfiConverterOptionTypeSearchSummary.write(value.summary, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchBatch_lift(_ buf: RustBuffer) throws -> SearchBatch {
    return try FfiConverterTypeSearchBatch.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchBatch_lower(_ value: SearchBatch) -> RustBuffer {
    return FfiConverterTypeSearchBatch.lower(value)
}

public struct SearchMatch {
    public var path: String
    public var lineNumber: UInt64
    public var line: String
    public var beforeContext: [String]
    public var afterContext: [String]
    /**
     * Offsets are relative to `line`.
     */
    public var submatches: [Submatch]
    /**
     * Byte offset of `line` within the original line when `line_truncated` cut a window.
     */
    public var lineOffset: UInt32
    public var lineTruncated: Bool

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(path: String, lineNumber: UInt64, line: String, beforeContext: [String], afterContext: [String],
                /* 
                    * Offsets are relative to `line`.
                    */ submatches: [Submatch],
                /* 
                    * Byte offset of `line` within the original line when `line_truncated` cut a window.
                    */ lineOffset: UInt32, lineTruncated: Bool)
    {
        self.path = path
        self.lineNumber = lineNumber
        self.line = line
        self.beforeContext = beforeContext
        self.afterContext = afterContext
        self.submatches = submatches
        self.lineOffset = lineOffset
        self.lineTruncated = lineTruncated
    }
}

extension SearchMatch: Equatable, Hashable {
    public static func == (lhs: SearchMatch, rhs: SearchMatch) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.lineNumber != rhs.lineNumber {
            return false
        }
        if lhs.line != rhs.line {
            return false
        }
        if lhs.beforeContext != rhs.beforeContext {
            return false
        }
        if lhs.afterContext != rhs.afterContext {
            return false
        }
        if lhs.submatches != rhs.submatches {
            return false
        }
        if lhs.lineOffset != rhs.lineOffset {
            return false
        }
        if lhs.lineTruncated != rhs.lineTruncated {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(lineNumber)
        hasher.combine(line)
        hasher.combine(beforeContext)
        hasher.combine(afterContext)
        hasher.combine(submatches)
        hasher.combine(lineOffset)
        hasher.combine(lineTruncated)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchMatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchMatch {
        return
            try SearchMatch(
                path: FfiConverterString.read(from: &buf),
                lineNumber: FfiConverterUInt64.read(from: &buf),
                line: FfiConverterString.read(from: &buf),
                beforeContext: FfiConverterSequenceString.read(from: &buf),
                afterContext: FfiConverterSequenceString.read(from: &buf),
                submatches: FfiConverterSequenceTypeSubmatch.read(from: &buf),
                lineOffset: FfiConverterUInt32.read(from: &buf),
                lineTruncated: FfiConverterBool.read(from: &buf)
            )
    }

    public static func write(_ value: SearchMatch, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterUInt64.write(value.lineNumber, into: &buf)
        FfiConverterString.write(value.line, into: &buf)
        FfiConverterSequenceString.write(value.beforeContext, into: &buf)
        FfiConverterSequenceString.write(value.afterContext, into: &buf)
        FfiConverterSequenceTypeSubmatch.write(value.submatches, into: &buf)
        FfiConverterUInt32.write(value.lineOffset, into: &buf)
        FfiConverterBool.write(value.lineTruncated, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchMatch_lift(_ buf: RustBuffer) throws -> SearchMatch {
    return try FfiConverterTypeSearchMatch.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchMatch_lower(_ value: SearchMatch) -> RustBuffer {
    return FfiConverterTypeSearchMatch.lower(value)
}

public struct SearchRequest {
    public var pattern: String
    public var paths: [String]
    public var caseInsensitive: Bool
    public var smartCase: Bool
    public var multiline: Bool
    public var includeGlobs: [String]
    public var excludeGlobs: [String]
    public var fileTypes: [String]
    public var respectGitignore: Bool
    /**
     * Apply `.gitignore` rules only inside a git repository (rg's default).
     */
    public var requireGit: Bool
    public var includeHidden: Bool
    public var beforeContext: UInt32
    public var afterContext: UInt32
    public var maxMatches: UInt32?
    public var maxFiles: UInt32?
    public var maxFileSizeBytes: UInt64?
    public var searchBinary: Bool
    /**
     * Longest line, in bytes, returned for a match or context line.
     */
    public var maxColumns: UInt32?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(pattern: String, paths: [String], caseInsensitive: Bool, smartCase: Bool, multiline: Bool, includeGlobs: [String], excludeGlobs: [String], fileTypes: [String], respectGitignore: Bool,
                /* 
                    * Apply `.gitignore` rules only inside a git repository (rg's default).
                    */ requireGit: Bool, includeHidden: Bool, beforeContext: UInt32, afterContext: UInt32, maxMatches: UInt32?, maxFiles: UInt32?, maxFileSizeBytes: UInt64?, searchBinary: Bool,
                /* 
                    * Longest line, in bytes, returned for a match or context line.
                    */ maxColumns: UInt32?)
    {
        self.pattern = pattern
        self.paths = paths
        self.caseInsensitive = caseInsensitive
        self.smartCase = smartCase
        self.multiline = multiline
        self.includeGlobs = includeGlobs
        self.excludeGlobs = excludeGlobs
        self.fileTypes = fileTypes
        self.respectGitignore = respectGitignore
        self.requireGit = requireGit
        self.includeHidden = includeHidden
        self.beforeContext = beforeContext
        self.afterContext = afterContext
        self.maxMatches = maxMatches
        self.maxFiles = maxFiles
        self.maxFileSizeBytes = maxFileSizeBytes
        self.searchBinary = searchBinary
        self.maxColumns = maxColumns
    }
}

extension SearchRequest: Equatable, Hashable {
    public static func == (lhs: SearchRequest, rhs: SearchRequest) -> Bool {
        if lhs.pattern != rhs.pattern {
            return false
        }
        if lhs.paths != rhs.paths {
            return false
        }
        if lhs.caseInsensitive != rhs.caseInsensitive {
            return false
        }
        if lhs.smartCase != rhs.smartCase {
            return false
        }
        if lhs.multiline != rhs.multiline {
            return false
        }
        if lhs.includeGlobs != rhs.includeGlobs {
            return false
        }
        if lhs.excludeGlobs != rhs.excludeGlobs {
            return false
        }
        if lhs.fileTypes != rhs.fileTypes {
            return false
        }
        if lhs.respectGitignore != rhs.respectGitignore {
            return false
        }
        if lhs.requireGit != rhs.requireGit {
            return false
        }
        if lhs.includeHidden != rhs.includeHidden {
            return false
        }
        if lhs.beforeContext != rhs.beforeContext {
            return false
        }
        if lhs.afterContext != rhs.afterContext {
            return false
        }
        if lhs.maxMatches != rhs.maxMatches {
            return false
        }
        if lhs.maxFiles != rhs.maxFiles {
            return false
        }
        if lhs.maxFileSizeBytes != rhs.maxFileSizeBytes {
            return false
        }
        if lhs.searchBinary != rhs.searchBinary {
            return false
        }
        if lhs.maxColumns != rhs.maxColumns {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pattern)
        hasher.combine(paths)
        hasher.combine(caseInsensitive)
        hasher.combine(smartCase)
        hasher.combine(multiline)
        hasher.combine(includeGlobs)
        hasher.combine(excludeGlobs)
        hasher.combine(fileTypes)
        hasher.combine(respectGitignore)
        hasher.combine(requireGit)
        hasher.combine(includeHidden)
        hasher.combine(beforeContext)
        hasher.combine(afterContext)
        hasher.combine(maxMatches)
        hasher.combine(maxFiles)
        hasher.combine(maxFileSizeBytes)
        hasher.combine(searchBinary)
        hasher.combine(maxColumns)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchRequest {
        return
            try SearchRequest(
                pattern: FfiConverterString.read(from: &buf),
                paths: FfiConverterSequenceString.read(from: &buf),
                caseInsensitive: FfiConverterBool.read(from: &buf),
                smartCase: FfiConverterBool.read(from: &buf),
                multiline: FfiConverterBool.read(from: &buf),
                includeGlobs: FfiConverterSequenceString.read(from: &buf),
                excludeGlobs: FfiConverterSequenceString.read(from: &buf),
                fileTypes: FfiConverterSequenceString.read(from: &buf),
                respectGitignore: FfiConverterBool.read(from: &buf),
                requireGit: FfiConverterBool.read(from: &buf),
                includeHidden: FfiConverterBool.read(from: &buf),
                beforeContext: FfiConverterUInt32.read(from: &buf),
                afterContext: FfiConverterUInt32.read(from: &buf),
                maxMatches: FfiConverterOptionUInt32.read(from: &buf),
                maxFiles: FfiConverterOptionUInt32.read(from: &buf),
                maxFileSizeBytes: FfiConverterOptionUInt64.read(from: &buf),
                searchBinary: FfiConverterBool.read(from: &buf),
                maxColumns: FfiConverterOptionUInt32.read(from: &buf)
            )
    }

    public static func write(_ value: SearchRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pattern, into: &buf)
        FfiConverterSequenceString.write(value.paths, into: &buf)
        FfiConverterBool.write(value.caseInsensitive, into: &buf)
        FfiConverterBool.write(value.smartCase, into: &buf)
        FfiConverterBool.write(value.multiline, into: &buf)
        FfiConverterSequenceString.write(value.includeGlobs, into: &buf)
        FfiConverterSequenceString.write(value.excludeGlobs, into: &buf)
        FfiConverterSequenceString.write(value.fileTypes, into: &buf)
        FfiConverterBool.write(value.respectGitignore, into: &buf)
        FfiConverterBool.write(value.requireGit, into: &buf)
        FfiConverterBool.write(value.includeHidden, into: &buf)
        FfiConverterUInt32.write(value.beforeContext, into: &buf)
        FfiConverterUInt32.write(value.afterContext, into: &buf)
        FfiConverterOptionUInt32.write(value.maxMatches, into: &buf)
        FfiConverterOptionUInt32.write(value.maxFiles, into: &buf)
        FfiConverterOptionUInt64.write(value.maxFileSizeBytes, into: &buf)
        FfiConverterBool.write(value.searchBinary, into: &buf)
        FfiConverterOptionUInt32.write(value.maxColumns, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchRequest_lift(_ buf: RustBuffer) throws -> SearchRequest {
    return try FfiConverterTypeSearchRequest.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchRequest_lower(_ value: SearchRequest) -> RustBuffer {
    return FfiConverterTypeSearchRequest.lower(value)
}

public struct SearchResult {
    public var matches: [SearchMatch]
    public var truncated: Bool
    public var cancelled: Bool
    public var filesSearched: UInt64
    public var elapsedMs: UInt64
    public var warnings: [SearchWarning]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(matches: [SearchMatch], truncated: Bool, cancelled: Bool, filesSearched: UInt64, elapsedMs: UInt64, warnings: [SearchWarning]) {
        self.matches = matches
        self.truncated = truncated
        self.cancelled = cancelled
        self.filesSearched = filesSearched
        self.elapsedMs = elapsedMs
        self.warnings = warnings
    }
}

extension SearchResult: Equatable, Hashable {
    public static func == (lhs: SearchResult, rhs: SearchResult) -> Bool {
        if lhs.matches != rhs.matches {
            return false
        }
        if lhs.truncated != rhs.truncated {
            return false
        }
        if lhs.cancelled != rhs.cancelled {
            return false
        }
        if lhs.filesSearched != rhs.filesSearched {
            return false
        }
        if lhs.elapsedMs != rhs.elapsedMs {
            return false
        }
        if lhs.warnings != rhs.warnings {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(matches)
        hasher.combine(truncated)
        hasher.combine(cancelled)
        hasher.combine(filesSearched)
        hasher.combine(elapsedMs)
        hasher.combine(warnings)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                matches: FfiConverterSequenceTypeSearchMatch.read(from: &buf),
                truncated: FfiConverterBool.read(from: &buf),
                cancelled: FfiConverterBool.read(from: &buf),
                filesSearched: FfiConverterUInt64.read(from: &buf),
                elapsedMs: FfiConverterUInt64.read(from: &buf),
                warnings: FfiConverterSequenceTypeSearchWarning.read(from: &buf)
            )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeSearchMatch.write(value.matches, into: &buf)
        FfiConverterBool.write(value.truncated, into: &buf)
        FfiConverterBool.write(value.cancelled, into: &buf)
        FfiConverterUInt64.write(value.filesSearched, into: &buf)
        FfiConverterUInt64.write(value.elapsedMs, into: &buf)
        FfiConverterSequenceTypeSearchWarning.write(value.warnings, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}

public struct SearchSummary {
    /**
     * The match limit was reached (more matches may or may not exist).
     */
    public var truncated: Bool
    public var cancelled: Bool
    public var filesSearched: UInt64
    public var elapsedMs: UInt64
    public var warnings: [SearchWarning]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The match limit was reached (more matches may or may not exist).
         */ truncated: Bool, cancelled: Bool, filesSearched: UInt64, elapsedMs: UInt64, warnings: [SearchWarning]
    ) {
        self.truncated = truncated
        self.cancelled = cancelled
        self.filesSearched = filesSearched
        self.elapsedMs = elapsedMs
        self.warnings = warnings
    }
}

extension SearchSummary: Equatable, Hashable {
    public static func == (lhs: SearchSummary, rhs: SearchSummary) -> Bool {
        if lhs.truncated != rhs.truncated {
            return false
        }
        if lhs.cancelled != rhs.cancelled {
            return false
        }
        if lhs.filesSearched != rhs.filesSearched {
            return false
        }
        if lhs.elapsedMs != rhs.elapsedMs {
            return false
        }
        if lhs.warnings != rhs.warnings {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(truncated)
        hasher.combine(cancelled)
        hasher.combine(filesSearched)
        hasher.combine(elapsedMs)
        hasher.combine(warnings)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchSummary {
        return
            try SearchSummary(
                truncated: FfiConverterBool.read(from: &buf),
                cancelled: FfiConverterBool.read(from: &buf),
                filesSearched: FfiConverterUInt64.read(from: &buf),
                elapsedMs: FfiConverterUInt64.read(from: &buf),
                warnings: FfiConverterSequenceTypeSearchWarning.read(from: &buf)
            )
    }

    public static func write(_ value: SearchSummary, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.truncated, into: &buf)
        FfiConverterBool.write(value.cancelled, into: &buf)
        FfiConverterUInt64.write(value.filesSearched, into: &buf)
        FfiConverterUInt64.write(value.elapsedMs, into: &buf)
        FfiConverterSequenceTypeSearchWarning.write(value.warnings, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchSummary_lift(_ buf: RustBuffer) throws -> SearchSummary {
    return try FfiConverterTypeSearchSummary.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchSummary_lower(_ value: SearchSummary) -> RustBuffer {
    return FfiConverterTypeSearchSummary.lower(value)
}

/**
 * A per-path problem that did not stop the search (unreadable file, binary file, ...).
 */
public struct SearchWarning {
    public var path: String
    public var message: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(path: String, message: String) {
        self.path = path
        self.message = message
    }
}

extension SearchWarning: Equatable, Hashable {
    public static func == (lhs: SearchWarning, rhs: SearchWarning) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(message)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchWarning: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchWarning {
        return
            try SearchWarning(
                path: FfiConverterString.read(from: &buf),
                message: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: SearchWarning, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchWarning_lift(_ buf: RustBuffer) throws -> SearchWarning {
    return try FfiConverterTypeSearchWarning.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchWarning_lower(_ value: SearchWarning) -> RustBuffer {
    return FfiConverterTypeSearchWarning.lower(value)
}

public struct Submatch {
    public var start: UInt32
    public var end: UInt32

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(start: UInt32, end: UInt32) {
        self.start = start
        self.end = end
    }
}

extension Submatch: Equatable, Hashable {
    public static func == (lhs: Submatch, rhs: Submatch) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSubmatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Submatch {
        return
            try Submatch(
                start: FfiConverterUInt32.read(from: &buf),
                end: FfiConverterUInt32.read(from: &buf)
            )
    }

    public static func write(_ value: Submatch, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSubmatch_lift(_ buf: RustBuffer) throws -> Submatch {
    return try FfiConverterTypeSubmatch.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSubmatch_lower(_ value: Submatch) -> RustBuffer {
    return FfiConverterTypeSubmatch.lower(value)
}

public enum OhMyGrepError {
    case InvalidPattern(message: String)

    case InvalidArguments(message: String)

    case PathNotFound(message: String)

    case Io(message: String)

    case InternalPanic(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeOhMyGrepError: FfiConverterRustBuffer {
    typealias SwiftType = OhMyGrepError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OhMyGrepError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .InvalidPattern(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .InvalidArguments(
                message: FfiConverterString.read(from: &buf)
            )

        case 3: return try .PathNotFound(
                message: FfiConverterString.read(from: &buf)
            )

        case 4: return try .Io(
                message: FfiConverterString.read(from: &buf)
            )

        case 5: return try .InternalPanic(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OhMyGrepError, into buf: inout [UInt8]) {
        switch value {
        case .InvalidPattern(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .InvalidArguments(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        case .PathNotFound(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(3))
        case .Io(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(4))
        case .InternalPanic(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(5))
        }
    }
}

extension OhMyGrepError: Equatable, Hashable {}

extension OhMyGrepError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeSearchSummary: FfiConverterRustBuffer {
    typealias SwiftType = SearchSummary?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSearchSummary.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSearchSummary.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeSearchMatch: FfiConverterRustBuffer {
    typealias SwiftType = [SearchMatch]

    static func write(_ value: [SearchMatch], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchMatch.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchMatch] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchMatch]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSearchMatch.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeSearchWarning: FfiConverterRustBuffer {
    typealias SwiftType = [SearchWarning]

    static func write(_ value: [SearchWarning], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchWarning.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchWarning] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchWarning]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSearchWarning.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeSubmatch: FfiConverterRustBuffer {
    typealias SwiftType = [Submatch]

    static func write(_ value: [Submatch], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSubmatch.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Submatch] {
        let len: Int32 = try readInt(&buf)
        var seq = [Submatch]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSubmatch.read(from: &buf))
        }
        return seq
    }
}

public func searchBlocking(request: SearchRequest, cancel: CancelToken) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(rustCallWithError(FfiConverterTypeOhMyGrepError.lift) {
        uniffi_ohmygrep_core_fn_func_search_blocking(
            FfiConverterTypeSearchRequest.lower(request),
            FfiConverterTypeCancelToken.lower(cancel), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ohmygrep_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_ohmygrep_core_checksum_func_search_blocking() != 48127 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ohmygrep_core_checksum_method_canceltoken_cancel() != 7756 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ohmygrep_core_checksum_method_canceltoken_is_cancelled() != 42323 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ohmygrep_core_checksum_method_searchsession_next_batch() != 21998 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ohmygrep_core_checksum_constructor_canceltoken_new() != 59277 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_ohmygrep_core_checksum_constructor_searchsession_start() != 20215 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
